### ISSUE TITLE
Doco Drive 

### ISSUE THREAD

**Issue by marylychee** [ssbc/ssb-ws#23]
Week 9 

I'd rate it from a 4 to 6. 
I think the context, explainer still needs work... 

in the beginning if someone just said ‘scuttlebutt webserver' - that still meant nothing to me... I added a link to Bean's secret island project as an example of context. 

Also not sure if I covered all methods. This looks pretty different to all the other ssb things I've looked at. 

[PR](https://github.com/ssbc/ssb-ws/pull/22)

**Comment by dominictarr** [comment]
cool, thanks!
